#!/bin/bash

source /usr/local/gromacs/bin/GMXRC
first_frame=0
last_frame=2500

for ((i=$first_frame;i<=$last_frame;i++)); do 
     echo 'com of group "site" plus com of group "UNK"'| gmx distance -s ./your/directory/pull3NNY_gtpnew.tpr -f ./your/directory/distg${i}.gro -n ./your/directory/UNK_gtp2.ndx -oall ./your/directory/dst${i}.xvg -select 
     echo -n "${i} " >> dist.txt 
     echo $( tail -n 1 ./your/directory/dst${i}.xvg ) >> dist.txt
     rm -r ./your/directory/gtp_perl/dst${i}.xvg
done
